### ISSUE TITLE
[TheMerge] Kintsugi tracking

### ISSUE THREAD

**Issue by yperbasis** [ledgerwatch/erigon#3078]
Tracking for [Kintsugi](https://hackmd.io/@n0ble/kintsugi-spec).

[Milestones](https://notes.ethereum.org/@djrtwo/kintsugi-milestones):
- [x] M0: Implementation started
  #2893
  #2900
  #2923
  #2962
  #2964
  #2978
  #2997
  #3053
  #3069
  #3074
  #3076
  #3077
  #3075
  #3083
  #3092
  #3112
  #3118
  #3151
  #3157
  #3174
  #3187
  #3202
  #3212
  #3220
  #3319
- [ ] M1: Spec Implemented
  - [x] pass all released consensus test vectors
     #3089
     #3103
  - [ ] Run against [mergemock](https://github.com/protolambda/mergemock)
  - [x] geth based [Engine API test cases](https://notes.ethereum.org/rmVErCfCRPKGqGkUe89-Kg?both) (not yet updated to Kintsugi v2)
  - [x] geth based [EIP 4399 test cases](https://notes.ethereum.org/dfVXr2h2TqWDKSXZaMwGTw?view)
  - [ ] additional [4399 test cases](https://github.com/marioevz/kintsugi_testing/tree/main/tests/EIP4399)
- [ ] M2: 1-to-1 Interop – One EL and one CL team pair off for basic interop testing
- [ ] M3: Many-to-Many Interop – 2 or more EL and CL teams perform interop testing
- [ ] M4: Weekly devnet – Weekly devnet build for more in depth testing
- [ ] M5: All-to-All persistent testnet – All ready EL and CL teams create a long-lived devnet
- [ ] M6: Kintsugi🍵 code released

**Comment by yperbasis** [comment]
Superseded by #3451.
